### ISSUE TITLE
Most of warning_print should should not be displayed.

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#338]
As @LecrisUT mentions at #336, `warning_print` is on by default. But I think most of them should not be displayed by default, but ideally this should be conditional. @LecrisUT, do you know a good way to make it conditional?

**Comment by LecrisUT** [comment]
[`getenv("SPGLIB_WARNING")`](https://en.cppreference.com/w/c/program/getenv). Probably more natural to be `SPGLIB_DEBUG` or `SPGLIB_LOG`

**Comment by kavanase** [comment]
Hi! Thanks for your work on this incredibly useful package.
Just to mention, we have also run into some of these warnings recently with our defects code [doped](https://doped.readthedocs.io/en/latest/) which relies on `spglib` through the `pymatgen` interface. In these cases, the result is still correct, just a stream of warnings are printed as `spglib` dynamically adjusts the tolerance. 
It would be much preferred if we could avoid these warnings!

**Comment by LecrisUT** [comment]
@kavanase can you review #457 and make sure any changes you want are there?

**Comment by kavanase** [comment]
@LecrisUT thanks very much for pushing forward with this!

Unfortunately it doesn't seem to fix our specific case:
<img width="744" alt="image" src="https://github.com/spglib/spglib/assets/51478689/1d260d5c-1112-4632-b609-6c7b8848b0ca">

(This is using the example data in the `doped` GitHub, with the `spglib` version from #457)
The full error output is:
```
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-02 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-02 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: ssm_get_exact_positions failed (attempt=0). (line 115, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/site_symmetry.c).
spglib: ssm_get_exact_positions failed (attempt=1). (line 115, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/site_symmetry.c).
spglib: ssm_get_exact_positions failed (attempt=2). (line 115, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/site_symmetry.c).
spglib: ssm_get_exact_positions failed (attempt=3). (line 115, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/site_symmetry.c).
spglib: ssm_get_exact_positions failed (attempt=4). (line 115, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/site_symmetry.c).
spglib: ssm_get_exact_positions failed. (line 479, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/refinement.c).
spglib: get_bravais_exact_positions_and_lattice failed. (line 336, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/refinement.c).
spglib: ref_get_exact_structure_and_symmetry failed. (line 82, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/determination.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 0 tolerance = 9.000000e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 1 tolerance = 8.550000e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 2 tolerance = 8.122500e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 3 tolerance = 7.716375e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 4 tolerance = 7.330556e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 5 tolerance = 6.964028e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
```

If I rerun this cell, the output gets shortened to:
```
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-02 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
```

I played around with trying to capture these warnings with `warnings`, `StringIO()` (for `stdout`/`stderr`), but none of these work either

**Comment by LecrisUT** [comment]
Sorry, I have pushed quite a few times commit `c4e959c` is not in my history, but in the most recent version that should fix all of these issues, all of the `__LINE__` and `__FILE__` were removed, and it seems you have installed a version, just shy of the main changes there. Can you try again? The commit should be 52910932d0086a959ee39325c5f6b91214064aa6

**Comment by kavanase** [comment]
Ok not sure what happened there (might have been when I was switching round `spglib` versions to check I had properly installed the new one), but I pulled again now and I'm still getting the same error (with commit `5291093`):
<img width="744" alt="image" src="https://github.com/spglib/spglib/assets/51478689/eba282e9-2c29-4e37-b8b5-f83d3442e40f">

I'm not sure if any of this is related to the way I've installed `spglib`. Here I'm just cloning the PR and then doing `pip install .`. I've made sure to `pip uninstall spglib` and `conda uninstall spglib` any previous installations, but not sure if my previous links or anything could be affecting this?

**Comment by LecrisUT** [comment]
Could you `import spglib` and print `spglib.__version__` just to double check that the `pip show` results are consistent with the version that the jupyter notebook is using?

Looking at the messages though, it seems "No point group was found" will still there, but maybe it doesn't need to be reported on

**Comment by kavanase** [comment]
Sure! Seems to be the correct version:
<img width="712" alt="image" src="https://github.com/spglib/spglib/assets/51478689/dce12f2e-4b13-4806-82b3-08822764dd71">

**Comment by kavanase** [comment]
Yes the `no point group was found` definitely doesn't need to be reported, as the automated tolerance adjusting in `spglib` then correctly identifies the point symmetry for this anyway

**Comment by LecrisUT** [comment]
This is weird, I am not sure why the changes were apparently not picked up. Do you have an `spglib` installed on the system? Can you run the jupyter notebook with `LD_LIBRARY_PATH` pointing to `site-packages/spglib/lib`, or `patchelf --add-rpath /path/to/site-packages/spglib/lib /path/to/_spglib.cpython-*.so`? Those are to make sure the library in the `pip` installation take priority (I did not consider a mechanism to switch between system/bundled preference). You can also verify that `spglib.spg_get_version_full` matches `spglib.__version__`

**Comment by kavanase** [comment]
Ok so printing `spglib.spg_get_version_full` showed that for some reason it was still loading some `2.3.1` files (I guess from `conda` installing them from before?) 
I tried setting `LD_LIBRARY_PATH` which didn't work:
![image](https://github.com/spglib/spglib/assets/51478689/01c86b1f-5d8b-418b-bfd6-e5c3b829aba3)

And `patchelf` didn't work for me on Mac, but setting `DYLD_LIBRARY_PATH` did partially:
![image](https://github.com/spglib/spglib/assets/51478689/9253d8f8-bdbd-4167-9ce3-2bf21c374a8d)

**Comment by kavanase** [comment]
As far as I can tell, these warnings are unnecessary? As in the end, `spglib` correctly determines the point symmetry.
Either way, they can't be caught as proper python warnings or from stdout/stderr it seems:
![image](https://github.com/spglib/spglib/assets/51478689/17a120a7-5eb5-4270-943b-1600bc5efc38)

**Comment by atztogo** [comment]
> As far as I can tell, these warnings are unnecessary?

If you get these messages, it is a bad sign that that tells that your crystal structure is distorted. To handle those distorted crystal structures, spglib adjusts tolerance to find a possible space group. Those message tells how spglib struggles for finding a space grouop. See https://arxiv.org/abs/1808.01590.

Those issues should be addressed. I hope I will find time for it soon. But you also have an opportunity to fix it by yourself reading the manuscript. You may not believe it, but when I started my research, spglib didn't exist.

**Comment by LecrisUT** [comment]
> To handle those distorted crystal structures, spglib adjusts tolerance to find a possible space group.

That is fine, but as a library, if spglib or the caller have methods to systematically address the distortion, than it shouldn't be throwing out such message without programmatic ways to disable them. Those make more sense in an example/standalone/debug environment.

My suggestion for that is to be a debug-like message. In this case I would say an `SPGLIB_INFO`, because these would make sense to be used at a user-level, compared to `SPGLIB_DEBUG`. We should reserve `SPGLIB_WARNING`, explicitly for when spglib actually errors out like when it runs out of memory or such.

At this point though, it seems that we should import a proper logger like [`spdlog`](https://github.com/gabime/spdlog). I am only familiar with C++ ones though, and I don't think there would be a good interface for a C logger with environment variable control and such.

**Comment by atztogo** [comment]
Thanks @LecrisUT for your valuable suggestion. I will categorize those into three, `SPGLIB_INFO`, `SPGLIB_DEBUG`, and `SPGLIB_WARNING`. I will make a PR for it, and please give me more detailed advice.

Use of external library may be overkill for spglib. But I also understand my senses are always slightly delayed from reality.

**Comment by kavanase** [comment]
Hi @atztogo, thanks for the input. 
Yes I've read the `spglib` paper and I'm aware of the reasons behind this warning. I understand it may be useful in certain cases to see this warning to flag issues with the underlying crystal structure. However the issue on our side is that this warning would hopefully be somewhat controllable (as @LecrisUT says) – not necessarily with an input flag or anything, but at least through the python `warnings` package or through `stdout`/`stderr`, neither of which is currently possible. 

Our use case is for determining the symmetries of defects in crystals, so there is always going to be some noise/distortion in the structure. In these cases, we would prefer to avoid printing many "No point group was found" warnings for the user when analysing several defects at once if possible – especially if the dynamic `symprec` routines manage to adjust and solve for the symmetry. Of course, if the code fails, then it is useful to print the warnings in that case, but otherwise we'd hope to avoid them in most cases I think.

**Comment by LecrisUT** [comment]
> but at least through the python warnings package or through stdout/stderr, neither of which is currently possible

If we make progress on the C++ interface, I know how to handle it more nicely to have pyrhon native warnings with `spdlog`.

In the meantime I hope hacking up different message prints would help. I couldn't find a straightforward way to classify info/warning/debug so there might take some iterations and feedback to get things right.

**Comment by atztogo** [comment]
>Our use case is for determining the symmetries of defects in crystals, so there is always going to be some noise/distortion in the structure.

For my purpose, it was preferred that spglib finds a possible space group even with adjusting tolerance value. Apart from the warning messages, but about your research, you may have to define your "noise" quantitatively and see if your way to use spglib is appropriate or not. I mean that your terminology of "symmetry of defects" may be weak, leading to potential self-deception. I strongly recommend you to discuss with your supervisors on this point.

**Comment by kavanase** [comment]
Yes finding an appropriate space group, even if adjusting tolerance is necessary, is definitely preferable for our case too. But ideally the warning messages about this would be controllable (and understandable to users).
About the noise, I agree that it's important that the symmetry is being correctly interpreted as this often isn't the case in the literature. I have tested this extensively and we already dynamically set appropriate `symprec` values for relaxed/un-relaxed defect structures with `spglib`, and manually verified that `spglib` is determining the correct point group symmetries across many cases; e.g. see https://doped.readthedocs.io/en/latest/thermodynamics_tutorial.html and/or our extensive test set
![Screenshot_2024-04-02-20-00-36-32_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/spglib/spglib/assets/51478689/3d953725-6887-4ddd-94f7-1f955308fa25)

The point symmetry determination fails for non-trivial supercell expansions that break the host cell symmetry upon defect introduction, but this is a minority of cases and I have warnings built in to catch these cases and inform the user -- but this is irrelevant to this `spglib` warning issue.

**Comment by atztogo** [comment]
@kavanase, thanks for your detailed information. But it is not what I wanted to mention. However this is not related to this specific issue, so I will not write more. Please first talk with your supervisors along with that I mentioned.
